language: python
python:
  - "3.3"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: python3 setup.py
# command to run tests, e.g. python setup.py test
script: python tests/prpr-test.py